/**
 * Generates the React Email preview entries from the email registry.
 *
 * Writes ONE preview file per email × applicable brand to
 * src/templates/<brand>/<email>.tsx. Each renders the LocaleTabs component,
 * which shows the metadata card (with the in-card language toggle) and every
 * language stacked. The React Email sidebar therefore shows a real <brand>
 * folder containing one entry per email — language is switched inside the card.
 *
 * Run: npm run generate
 */
import fs from 'node:fs'
import path from 'node:path'
import { fileURLToPath } from 'node:url'
import { EMAILS } from '../src/registry'
import { brandsForTag } from '../src/brand'

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..')
const templatesDir = path.join(root, 'src', 'templates')

// Clean and recreate
fs.rmSync(templatesDir, { recursive: true, force: true })
fs.mkdirSync(templatesDir, { recursive: true })

let count = 0
for (const email of EMAILS) {
  for (const brand of brandsForTag(email.tag)) {
    const brandDir = path.join(templatesDir, brand)
    fs.mkdirSync(brandDir, { recursive: true })

    const file = path.join(brandDir, `${email.id}.tsx`)
    const content = `// AUTO-GENERATED by scripts/generate-previews.ts — do not edit.
// Edit the source email at src/emails/${email.id}.tsx instead.
import { LocaleTabs } from '../../components/LocaleTabs'

export default function Preview() {
  return <LocaleTabs email="${email.id}" brand="${brand}" />
}
`
    fs.writeFileSync(file, content)
    count++
  }
}

console.log(`✓ Generated ${count} preview(s) across ${EMAILS.length} email(s) in src/templates/`)
