/**
 * Generates the React Email preview entries from the email registry.
 *
 * For every email × applicable brand × brand-locale, writes a thin preview file
 * to src/templates/<brand>/<email>-<locale>.tsx. The React Email sidebar then
 * groups these by brand folder (the brand toggle) with one entry per language
 * (the language toggle).
 *
 * Run: npm run generate
 */
import fs from 'node:fs'
import path from 'node:path'
import { fileURLToPath } from 'node:url'
import { EMAILS } from '../src/registry'
import { brandsForTag } from '../src/brand'
import { BRAND_LOCALES } from '../src/i18n'

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..')
const templatesDir = path.join(root, 'src', 'templates')

// Clean and recreate
fs.rmSync(templatesDir, { recursive: true, force: true })
fs.mkdirSync(templatesDir, { recursive: true })

let count = 0
for (const email of EMAILS) {
  for (const brand of brandsForTag(email.tag)) {
    const brandDir = path.join(templatesDir, brand)
    fs.mkdirSync(brandDir, { recursive: true })

    for (const locale of BRAND_LOCALES[brand]) {
      const file = path.join(brandDir, `${email.id}-${locale}.tsx`)
      const content = `// AUTO-GENERATED by scripts/generate-previews.ts — do not edit.
// Edit the source email at src/emails/${email.id}.tsx instead.
import Email from '../../emails/${email.id}'

export default function Preview() {
  return <Email brand="${brand}" locale="${locale}" preview />
}
`
      fs.writeFileSync(file, content)
      count++
    }
  }
}

console.log(`✓ Generated ${count} preview(s) across ${EMAILS.length} email(s) in src/templates/`)
