// AUTO-GENERATED by scripts/generate-previews.ts — do not edit.
// Edit the source email at src/emails/team-invite.tsx instead.
import Email from '../../emails/team-invite'

export default function Preview() {
  return <Email brand="eleaseloop" locale="en" preview />
}
