// AUTO-GENERATED by scripts/generate-previews.ts — do not edit.
// Edit the source email at src/emails/team-invite.tsx instead.
import { LocaleTabs } from '../../components/LocaleTabs'

export default function Preview() {
  return <LocaleTabs email="team-invite" brand="fillit" />
}
