// AUTO-GENERATED by scripts/generate-previews.ts — do not edit.
// Edit the source email at src/emails/signatory-added.tsx instead.
import Email from '../../../emails/signatory-added'

export default function Preview() {
  return <Email brand="eleaseloop" locale="it" preview />
}
